#!/usr/bin/env python

from __future__ import print_function

import sys
import textwrap
import emk

def usage():
    print("emk [args...]")
    print(textwrap.dedent(emk.main.__doc__))

if __name__ == "__main__":
    if "-h" in sys.argv:
        usage()
    else:
        sys.exit(emk.main(sys.argv[1:]))
